import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: 'var(--color-brand)',
        'brand-dark': 'var(--color-brand-dark)',
        'brand-deep': 'var(--color-brand-deep)',
        'brand-light': 'var(--color-brand-light)',
        agents: 'var(--color-agents)',
        'agents-dark': 'var(--color-agents-dark)',
        'agents-light': 'var(--color-agents-light)',
        website: 'var(--color-website)',
        'website-dark': 'var(--color-website-dark)',
        'website-light': 'var(--color-website-light)',
        marketing: 'var(--color-marketing)',
        'marketing-dark': 'var(--color-marketing-dark)',
        'marketing-light': 'var(--color-marketing-light)',
        success: {
          DEFAULT: 'var(--color-success)',
          dark: 'var(--color-success-dark)',
          surface: 'var(--color-success-surface)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
          dark: 'var(--color-warning-dark)',
          surface: 'var(--color-warning-surface)',
        },
        error: {
          DEFAULT: 'var(--color-error)',
          dark: 'var(--color-error-dark)',
          surface: 'var(--color-error-surface)',
        },
        info: {
          DEFAULT: 'var(--color-info)',
          dark: 'var(--color-info-dark)',
          surface: 'var(--color-info-surface)',
        },
        border: {
          default: 'var(--border-default)',
          subtle: 'var(--border-subtle)',
          strong: 'var(--border-strong)',
          focus: 'var(--border-focus)',
          agents: 'var(--border-agents)',
          website: 'var(--border-website)',
          marketing: 'var(--border-marketing)',
        },
        surface: {
          page: 'var(--surface-page)',
          base: 'var(--surface-base)',
          raised: 'var(--surface-raised)',
          overlay: 'var(--surface-overlay)',
          sunken: 'var(--surface-sunken)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          disabled: 'var(--text-disabled)',
          inverse: 'var(--text-inverse)',
          brand: 'var(--text-brand)',
          agents: 'var(--text-agents)',
          website: 'var(--text-website)',
          marketing: 'var(--text-marketing)',
        },
        primary: 'var(--color-brand)',
      },
      fontFamily: {
        display: ['var(--font-display)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        sans: ['var(--font-sans)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        '2xs': 'var(--text-2xs)',
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
        'display-lg': 'var(--text-display-lg)',
        'display-xl': 'var(--text-display-xl)',
        'display-2xl': 'var(--text-display-2xl)',
      },
      fontWeight: {
        normal: 'var(--font-regular)',
        medium: 'var(--font-medium)',
        semibold: 'var(--font-semibold)',
        bold: 'var(--font-bold)',
      },
      lineHeight: {
        tight: 'var(--leading-tight)',
        snug: 'var(--leading-snug)',
        normal: 'var(--leading-normal)',
        relaxed: 'var(--leading-relaxed)',
      },
      letterSpacing: {
        tight: 'var(--tracking-tight)',
        normal: 'var(--tracking-normal)',
        wide: 'var(--tracking-wide)',
        wider: 'var(--tracking-wider)',
      },
      backgroundImage: {
        'gradient-brand': 'var(--gradient-brand)',
        'gradient-brand-subtle': 'var(--gradient-brand-subtle)',
        'gradient-brand-vertical': 'var(--gradient-brand-vertical)',
        'gradient-agents': 'var(--gradient-agents)',
        'gradient-website': 'var(--gradient-website)',
        'gradient-marketing': 'var(--gradient-marketing)',
        'gradient-glow-top': 'var(--gradient-glow-top)',
        'gradient-glow-bottom': 'var(--gradient-glow-bottom)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        brand: 'var(--shadow-brand)',
        agents: 'var(--shadow-agents)',
        website: 'var(--shadow-website)',
        marketing: 'var(--shadow-marketing)',
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        base: 'var(--duration-base)',
        slow: 'var(--duration-slow)',
        slower: 'var(--duration-slower)',
      },
      transitionTimingFunction: {
        default: 'var(--ease-default)',
        in: 'var(--ease-in)',
        out: 'var(--ease-out)',
        spring: 'var(--ease-spring)',
        bounce: 'var(--ease-bounce)',
      },
      width: {
        sidebar: 'var(--sidebar-width)',
        'sidebar-collapsed': 'var(--sidebar-collapsed-width)',
      },
      height: {
        dock: 'var(--dock-height)',
      },
      maxWidth: {
        content: 'var(--content-max-width)',
      },
      zIndex: {
        sidebar: 'var(--z-sidebar)',
        dock: 'var(--z-dock)',
        dropdown: 'var(--z-dropdown)',
        modal: 'var(--z-modal)',
        toast: 'var(--z-toast)',
        tooltip: 'var(--z-tooltip)',
      },
    },
  },
  plugins: [],
};

export default config;
